Ir para o conteúdo
Comunidade DEV
Procurar...

Conecte-se
Criar Conta

50

9

48

Imagem da capa de Como habilitar as ações do GitHub no seu perfil README para um gráfico de contribuição devoradora de cobras 🐍
Michelle Mannering
Michelle Mannering
postado em28 de junho. de 2021 • Atualizado em23 fev.

Como habilitar o GitHub Actions no seu perfil README para um gráfico de contribuição devoradora de cobras 🐍
#
github
#
remarcação
#
Código aberto
#
tutorial
Git Good (Série de 9 Partes)
1
Usando a CLI do GitHub para atualizar seu repositório
2
Como criar e fixar uma essência no GitHub
...
mais 5 peças...
8
Como usar o GitHub Pages para hospedar seu site, mesmo com vários repositórios
9
Como criar um README de perfil para sua organização
Lots of people have been talking about and sharing their GitHub Profile READMEs. It was a project we launched last year and developers are loving it. As this feature became more popular, more developers were building templates, plugins, and apps for you to use on your profile.

This post from Supritha caught my attention. I like the way they talk about various pieces of code to have on your GitHub Profile README.

surpresa 
How to have an awesome GitHub profile ?
Supritha Ravishankar ・ Jun 8 '21 ・ 5 min read
#github #markdown #opensource #git
One of the comments from Guillaume Falourd pointed to a really cool project from Platane.

Logo do GitHub Platane / snk
🟩⬜ Generates a snake game from a github user contributions graph and output a screen capture as animated svg or gif
snk
Mercado GitHub definições de tipo estilo de código

Generates a snake game from a github user contributions graph



Pull a github user's contribution graph Make it a snake Game, generate a snake path where the cells get eaten in an orderly fashion.

Generate a gif or svg image.

Available as github action. Automatically generate a new image at the end of the day. Which makes for great github profile readme

Usage
github action

- uses: Platane/snk@master
  with:
    # github user name to read the contribution graph from (**required**)
    # using action context var `github.repository_owner` or specified user
    github_user_name: ${{ github.repository_owner }}

    # path of the generated gif file
    # If left empty, the gif file will not be generated
    gif_out_path: dist/github-snake.gif

    # path of the generated svg file
    # If left empty, the svg file will not be generated
    svg_out_path: dist/github-snake.svg
example with cron job

interactive demo


platane.github.io/snk

local

npm install
npm
…
View on GitHub
Ele usa o GitHub Actions para criar e atualizar o gráfico de contribuição de um usuário e, em seguida, uma cobra come todas as suas contribuições. A saída gera um arquivo gif, que você pode mostrar no README do seu perfil do GitHub. Achei isso muito legal, então comecei a adicionar isso ao meu perfil.

Etapa 1. Configurando as ações do GitHub
A primeira coisa que você deseja garantir antes de iniciar este projeto é que você tenha a configuração do GitHub Actions. Vá para o seu perfil e verifique se a guia "Ações" está disponível. Todos agora devem ter esse recurso.

Botão de ações

Em seguida, vá para o Platane's Action (disponível no Marketplace) e faça uma cópia do código. Você precisará adicionar este snippet em seu arquivo de ações.

Etapa 2. Criando seu arquivo yaml do GitHub Actions
Esta é definitivamente a parte em que eu fiquei preso. Ao olhar para o código, não sabia exatamente onde adicionar as linhas de código mencionadas no Marketplace .

Depois de ver como o Platane configurou o arquivo Actions, consegui gerar o código (com uma pequena ajuda de Bdougie , é claro).

Eu adicionei o trecho de código completo abaixo e adicionei muitos comentários (espero que seja fácil de entender).

Você pode copiar esse código diretamente para um arquivo *.yml em branco. Certifique-se de criar um novo arquivo *.yml no seguinte diretório:

YOUR_GITHUB_USERNAME --> .github --> fluxos de trabalho --> FILE_NAME.yml

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Etapa 3. Executar ações do GitHub
Depois de adicionar o código acima e confirmá-lo, vá para a guia Ações. Em "Workflows", você deverá ver a ação "Generate Snake" criada acima.

Fluxo de trabalho

Clique em "Executar fluxo de trabalho" e veja seu fluxo de trabalho ser executado. Você pode até expandir seu fluxo de trabalho e ver o que está acontecendo em tempo real.


GIF
Ações em execução

Depois que seu fluxo de trabalho terminar de ser executado, você deverá ter recebido uma marca de seleção ✅ "compilar" verde. Se sim, isso significa que sua ação está funcionando bem. Caso contrário, você terá que passar pelo código e ver onde estão os erros. O status "build" deve fornecer alguma indicação de onde estão seus erros. Você também pode compará-lo com o arquivo yaml no meu perfil do GitHub README .

Construir verde

If you have the green "build" ✅ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.


GIF
Saída de código

Step 4. Adding a contribution-eating snake to your profile
Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!


GIF
Comendo Cobras
Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?

Git Good (9 Part Series)
1
Using the GitHub CLI to update your repo
2
How to create and pin a gist on GitHub
...
5 more parts...
8
How to use GitHub Pages to host your website, even with multiple repos
9
How to create a Profile README for your Organisation
Discussion (17)
Se inscrever
foto
Adicionar à discussão
 
imagem de perfil do msoftware
Michael jentsch
•
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
 likes
Reply
 
gustavohgmartins profile image
Gustavo Martins
•
Sep 3 '21

Awsome! How did you change the background-color?


Like
Reply
 
mishmanners profile image
Michelle Mannering 
•
Sep 3 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
 like
Thread
gustavohgmartins profile image
Gustavo Martins
•
Sep 3 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilá


2
 likes
Thread
mishmanners profile image
Michelle Mannering 
•
Sep 3 '21

Awesome! Glad to be of help 😄


1
 like
Reply
 
bpolaswar profile image
Bhumesh Polaswar
•
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.


2
 likes
Reply
 
wkylin profile image
wkylin.w
•
May 1

Here's mine:
github.com/wkylin


1
 like
Reply
 
laurasiiia profile image
Laura
•
Jan 2 • Edited on Jan 2

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia


1
 like
Reply
 
mishmanners profile image
Michelle Mannering 
•
Jan 4

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people 😄


1
 like
Reply
 
adityamangal1 profile image
Aditya Mangal
•
Jul 22 '21

Awesome Tutorial! 🐍


1
 like
Reply
 
viveeeeeek profile image
VivekS.
•
Oct 2 '21

Awesome!


1
 like
Reply
 
imagem de perfil de zieldecastro
Josiel de Castro Goudinho
•
Sep 14 '21 • Edited on Sep 14

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/


1
 like
Reply
 
imagem de perfil do shasank27
Shasank Periwal
•
Aug 8 '21 • Edited on Aug 8

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27


1
 like
Reply
 
imagem de perfil de mishmanners
Michelle Mannering 
•
Sep 6 '21 • Edited on Sep 6

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.


1
 like
Reply
 
imagem de perfil de ichchhagupta
Ichchha Gupta
•
Dec 14 '21

Can you please help me in figuring out where to find my actions file mentioned in step 1, so that I can add the required code.


Like
Reply
 
imagem de perfil de mishmanners
Michelle Mannering 
•
Dec 15 '21

Actions is a feature you'll need to enable for your repo. When you go to your repo, you'll notice a tab called "Actions" that should be next to the "Pull requests" tab. Click the "Actions" tab then you can setup Actions from there.


1
 like
Reply
 
imagem de perfil de adityatakekar
Aditya Thakekar
•
Dec 24 '21

works great. thanks a ton.


Like
Reply
Code of Conduct • Report abuse
Read next
imagem de perfil sneh27
Desmistificando o Linux: O propósito de /bin, /usr/bin e /usr/local/bin
Sneh Chauhan -23 de abril

imagem de perfil do lazypro
O mistério da indexação do MongoDB
Chun Ting Wu -25 de abril

imagem de perfil de ben
Remova todos os seus branches git locais, mas mantenha main
Ben Halpern -19 de abril

imagem de perfil de janvierjr
Seus ícones provavelmente devem ser arquivos SVG. Aqui está o porquê.
Bernie Janeiro Jr. -24 de abril


Michelle Mannering
Seguir
Advogado Desenvolvedor | Rainha Hackathon | Palestrante Internacional
LOCALIZAÇÃO
Austrália
EDUCAÇÃO
A Universidade de Melbourne
TRABALHAR
Desenvolvedor Advocate no GitHub
JUNTOU
28 de maio. de 2020
Mais de Michelle Mannering
Entenda seu código usando o GitHub Copilot
# github # ai # produtividade # tutorial
Como traduzir código para outros idiomas usando o GitHub Copilot
# iniciantes # codenewbie # tutorial # produtividade
Como criar uma comunidade de código aberto saudável e sustentável
# github # código aberto # tutorial

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Comunidade DEV— Uma rede social construtiva e inclusiva para desenvolvedores de software. Com você a cada passo de sua jornada.

Construído emFormulário- aCódigo abertosoftware que alimentaDEVe outras comunidades inclusivas.

Feito com amor eRuby nos trilhos. Comunidade DEV © 2016 - 2022.
